# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Alarma.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication, QMainWindow, QTableWidgetItem, QMessageBox, QComboBox
from PyQt5.QtMultimedia import QMediaPlayer, QMediaContent
from PyQt5.QtCore import QUrl
import os, sys
from PyQt5 import uic
from PyQt5.QtCore import QTimer, QTime
import time 
import pygame

class Alarma(QMainWindow):
    
    def __init__(self):
        ruta = os.path.dirname ( os.path.abspath ( __file__ ) ) + r"\Alarma.ui"
        QMainWindow.__init__(self)
        uic.loadUi(ruta,self)
        
        self.timer = QTimer(self)
        self.timer.timeout.connect(self.update_time)
        self.timer.start(1000)
        self.update_time()  # Llamada inicial para mostrar la hora de inmediato
        self.lcdNumber.setDigitCount(8)
        
        # Conectar botones a funciones correspondientes
        self.btnCrear.clicked.connect(self.agregarAlarma)
        self.btnSeleccionar.clicked.connect(self.cargarDatosSeleccionados)
        self.btnActualizar.clicked.connect(self.actualizarAlarma)
        self.btnEliminar.clicked.connect(self.confirmarEliminarAlarma)
        self.btnRegresar.clicked.connect(self.cerrarVentana)
        
        # Deshabilitar todos los botones excepto "Crear" y "Regresar" al inicio
        self.deshabilitarBotones()
        self.btnCrear.setEnabled(True)
        self.btnRegresar.setEnabled(True)
        
        # Configurar señales y slots para actualizar estado de los botones
        self.tblAlarma.itemSelectionChanged.connect(self.actualizarEstadoBotones)
        self.cbHorasAlarma.currentIndexChanged.connect(self.actualizarEstadoBotones)
        self.cbMinutosAlarma.currentIndexChanged.connect(self.actualizarEstadoBotones)
        self.cbSonido.currentIndexChanged.connect(self.actualizarEstadoBotones)
        self.txtNombre.textChanged.connect(self.actualizarEstadoBotones)
        
        # Configurar QTableWidget tblAlarma
        self.tblAlarma.setColumnCount(4)  # Establecer 4 columnas
        headers = ["Hora", "Minuto", "Sonido", "Nombre"]  # Encabezados de columnas
        self.tblAlarma.setHorizontalHeaderLabels(headers)
        
        # Inicializar el reproductor de medios
        pygame.mixer.init()

    def deshabilitarBotones(self):
        # Función para deshabilitar todos los botones excepto "Crear" y "Regresar"
        self.btnSeleccionar.setEnabled(False)
        self.btnActualizar.setEnabled(False)
        self.btnEliminar.setEnabled(False)
    
    def habilitarBotones(self):
        # Función para habilitar todos los botones
        self.btnSeleccionar.setEnabled(True)
        self.btnActualizar.setEnabled(True)
        self.btnEliminar.setEnabled(True)
    
    def actualizarEstadoBotones(self):
        # Actualizar el estado de los botones según el estado del QTableWidget y campos de entrada
        if self.tblAlarma.rowCount() == 0:
            # Si no hay filas en el QTableWidget
            self.deshabilitarBotones()
            self.btnCrear.setEnabled(True)
            self.btnRegresar.setEnabled(True)
        else:
            selected_row = self.tblAlarma.currentRow()
            if selected_row == -1:
                # Si no se ha seleccionado ninguna fila
                self.deshabilitarBotones()
                self.btnSeleccionar.setEnabled(True)
                self.btnRegresar.setEnabled(True)
            else:
                # Si se ha seleccionado una fila
                self.btnRegresar.setEnabled(True)
                self.btnSeleccionar.setEnabled(True)
                if self.camposModificados():
                    # Si se han modificado los campos
                    self.btnActualizar.setEnabled(True)
                else:
                    # Si no se han modificado los campos
                    self.btnActualizar.setEnabled(False)
    
    def camposModificados(self):
        # Función para verificar si los campos de edición han sido modificados
        hora_actual = self.tblAlarma.item(self.tblAlarma.currentRow(), 0).text() if self.tblAlarma.currentRow() != -1 else ""
        minuto_actual = self.tblAlarma.item(self.tblAlarma.currentRow(), 1).text() if self.tblAlarma.currentRow() != -1 else ""
        sonido_actual = self.tblAlarma.item(self.tblAlarma.currentRow(), 2).text() if self.tblAlarma.currentRow() != -1 else ""
        nombre_actual = self.tblAlarma.item(self.tblAlarma.currentRow(), 3).text() if self.tblAlarma.currentRow() != -1 else ""
        
        return (hora_actual != self.cbHorasAlarma.currentText() or
                minuto_actual != self.cbMinutosAlarma.currentText() or
                sonido_actual != self.cbSonido.currentText() or
                nombre_actual != self.txtNombre.text())
        
    def limpiarCampos(self):
        # Limpiar los campos de entrada
        self.cbHorasAlarma.setCurrentIndex(0)  # Establecer el índice a 0 (primer elemento)
        self.cbMinutosAlarma.setCurrentIndex(0)
        self.cbSonido.setCurrentIndex(0)
        self.txtNombre.clear()  # Limpiar el texto del QLineEdit
        
    def agregarAlarma(self):
        # Obtener los valores de los campos
        hora = self.cbHorasAlarma.currentText()
        minuto = self.cbMinutosAlarma.currentText()
        sonido = self.cbSonido.currentText()
        nombre = self.txtNombre.text()
        
        # Calcular tiempo restante para la alarma
        tiempo_restante = self.calcularTiempoRestante(int(hora), int(minuto))
        
        # Mostrar la notificación con el tiempo restante
        self.mostrarNotificacion(tiempo_restante['horas'], tiempo_restante['minutos'])
        
        # Insertar una nueva fila en el QTableWidget
        rowPosition = self.tblAlarma.rowCount()
        self.tblAlarma.insertRow(rowPosition)
        
        # Establecer los elementos individuales en cada columna usando QTableWidgetItem
        item_hora = QtWidgets.QTableWidgetItem(hora)
        item_minuto = QtWidgets.QTableWidgetItem(minuto)
        item_sonido = QtWidgets.QTableWidgetItem(sonido)
        item_nombre = QtWidgets.QTableWidgetItem(nombre)
        
        self.tblAlarma.setItem(rowPosition, 0, item_hora)
        self.tblAlarma.setItem(rowPosition, 1, item_minuto)
        self.tblAlarma.setItem(rowPosition, 2, item_sonido)
        self.tblAlarma.setItem(rowPosition, 3, item_nombre)
        
        # Limpiar campos después de agregar
        self.limpiarCampos()
        
        # Habilitar todos los botones después de agregar
        self.habilitarBotones()
    
    def calcularTiempoRestante(self, hora, minuto):
        # Calcular el tiempo restante para la alarma
        hora_actual = QtCore.QTime.currentTime()
        alarma = QtCore.QTime(hora, minuto)
        
        if alarma < hora_actual:
            # Si la alarma es para el día siguiente
            diferencia_horas = (24 - hora_actual.hour()) + hora
            diferencia_minutos = minuto - hora_actual.minute()
        else:
            diferencia_horas = hora - hora_actual.hour()
            diferencia_minutos = minuto - hora_actual.minute()
        
        if diferencia_minutos < 0:
            diferencia_minutos += 60
            diferencia_horas -= 1
        
        return {'horas': diferencia_horas, 'minutos': diferencia_minutos}
    
    def mostrarNotificacion(self, horas, minutos):
        # Crear un QMessageBox sin botones ni sonido
        notificacion = QtWidgets.QMessageBox(self)
        notificacion.setWindowTitle("Tiempo Alarma")
        notificacion.setText(f"La alarma sonará dentro de {horas} horas y {minutos} minutos.")
        notificacion.setIcon(QtWidgets.QMessageBox.Information)
        
        # Configurar para que desaparezca después de 15 segundos
        timer = QtCore.QTimer(notificacion)
        timer.timeout.connect(notificacion.close)
        timer.start(5000)  # 5 segundos
        
        # Mostrar la notificación
        notificacion.exec_()
    
    def cargarDatosSeleccionados(self):
        # Obtener la fila seleccionada
        selected_row = self.tblAlarma.currentRow()
        
        if selected_row != -1:  # Verificar si hay una fila seleccionada
            # Obtener los elementos de la fila seleccionada
            hora = self.tblAlarma.item(selected_row, 0).text()
            minuto = self.tblAlarma.item(selected_row, 1).text()
            sonido = self.tblAlarma.item(selected_row, 2).text()
            nombre = self.tblAlarma.item(selected_row, 3).text()
            
            # Establecer los valores en los campos de entrada
            self.cbHorasAlarma.setCurrentText(hora)
            self.cbMinutosAlarma.setCurrentText(minuto)
            self.cbSonido.setCurrentText(sonido)
            self.txtNombre.setText(nombre)
        
    def actualizarAlarma(self):
        # Obtener la fila seleccionada
        selected_row = self.tblAlarma.currentRow()
        
        if selected_row != -1:  # Verificar si hay una fila seleccionada
            # Obtener los nuevos valores de los campos de entrada
            hora = self.cbHorasAlarma.currentText()
            minuto = self.cbMinutosAlarma.currentText()
            sonido = self.cbSonido.currentText()
            nombre = self.txtNombre.text()
            
            # Actualizar los elementos en la fila seleccionada
            self.tblAlarma.setItem(selected_row, 0, QtWidgets.QTableWidgetItem(hora))
            self.tblAlarma.setItem(selected_row, 1, QtWidgets.QTableWidgetItem(minuto))
            self.tblAlarma.setItem(selected_row, 2, QtWidgets.QTableWidgetItem(sonido))
            self.tblAlarma.setItem(selected_row, 3, QtWidgets.QTableWidgetItem(nombre))
            
            # Limpiar campos después de actualizar
            self.limpiarCampos()
            
            # Habilitar todos los botones después de actualizar
            self.habilitarBotones()
    
    def confirmarEliminarAlarma(self):
        # Obtener la fila seleccionada
        selected_row = self.tblAlarma.currentRow()
        
        if selected_row != -1:  # Verificar si hay una fila seleccionada
            # Mostrar un cuadro de diálogo para confirmar la eliminación
            mensaje = "¿Está seguro de eliminar la alarma?"
            respuesta = QtWidgets.QMessageBox.question(self, 'Eliminar Alarma', mensaje,
                                                       QtWidgets.QMessageBox.Yes | QtWidgets.QMessageBox.No,
                                                       QtWidgets.QMessageBox.No)
            if respuesta == QtWidgets.QMessageBox.Yes:
                self.tblAlarma.removeRow(selected_row)
                
                # Después de eliminar, verificar y actualizar estado de botones
                self.actualizarEstadoBotones()
    
    def cerrarVentana(self):
        # Cerrar la ventana actual
        self.close()
    
    def update_time(self):
        # Obtener la hora actual
        hora_actual = QTime.currentTime()
        
        # Formatear la hora como una cadena de texto
        hora_formateada = hora_actual.toString("hh:mm:ss")
        
        # Mostrar la hora en el QLCDNumber
        self.lcdNumber.display(hora_formateada)
        
        # Verificar si alguna alarma coincide con la hora actual
        for row in range(self.tblAlarma.rowCount()):
            hora_alarma = int(self.tblAlarma.item(row, 0).text())
            minuto_alarma = int(self.tblAlarma.item(row, 1).text())
            
            if (hora_actual.hour() == hora_alarma and
                hora_actual.minute() == minuto_alarma and
                hora_actual.second() == 0):
                self.reproducirSonido()
    
    def reproducirSonido(self):
        # Ruta del archivo de sonido "Sonido 01"
        sonido_ruta = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'Sonido 04.mp3')
        
        # Cargar el archivo de sonido
        pygame.mixer.music.load(sonido_ruta)
        
        # Reproducir el archivo de sonido
        pygame.mixer.music.play()
    
    def setupUi(self, Alarma):
        Alarma.setObjectName("Alarma")
        Alarma.resize(779, 679)
        self.centralwidget = QtWidgets.QWidget(Alarma)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 801, 671))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("Alarma_Fondo.png"))
        self.label.setObjectName("label")
        self.lcdNumber = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber.setGeometry(QtCore.QRect(100, 20, 561, 241))
        self.lcdNumber.setObjectName("lcdNumber")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(50, 280, 271, 16))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.cbMinutosAlarma = QtWidgets.QComboBox(self.centralwidget)
        self.cbMinutosAlarma.setGeometry(QtCore.QRect(160, 340, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(11)
        self.cbMinutosAlarma.setFont(font)
        self.cbMinutosAlarma.setObjectName("cbMinutosAlarma")
        self.cbMinutosAlarma.addItem("")
        self.cbMinutosAlarma.addItem("")
        self.cbMinutosAlarma.addItem("")
        self.cbMinutosAlarma.addItem("")
        self.cbMinutosAlarma.addItem("")
        self.cbMinutosAlarma.addItem("")
        self.cbMinutosAlarma.addItem("")
        self.cbMinutosAlarma.addItem("")
        self.cbMinutosAlarma.addItem("")
        self.cbMinutosAlarma.addItem("")
        self.cbMinutosAlarma.addItem("")
        self.cbMinutosAlarma.addItem("")
        self.cbMinutosAlarma.addItem("")
        self.cbMinutosAlarma.addItem("")
        self.cbMinutosAlarma.addItem("")
        self.cbMinutosAlarma.addItem("")
        self.cbMinutosAlarma.addItem("")
        self.cbMinutosAlarma.addItem("")
        self.cbMinutosAlarma.addItem("")
        self.cbMinutosAlarma.addItem("")
        self.cbMinutosAlarma.addItem("")
        self.cbMinutosAlarma.addItem("")
        self.cbMinutosAlarma.addItem("")
        self.cbMinutosAlarma.addItem("")
        self.cbMinutosAlarma.addItem("")
        self.cbMinutosAlarma.addItem("")
        self.cbMinutosAlarma.addItem("")
        self.cbMinutosAlarma.addItem("")
        self.cbMinutosAlarma.addItem("")
        self.cbMinutosAlarma.addItem("")
        self.cbMinutosAlarma.addItem("")
        self.cbMinutosAlarma.addItem("")
        self.cbMinutosAlarma.addItem("")
        self.cbMinutosAlarma.addItem("")
        self.cbMinutosAlarma.addItem("")
        self.cbMinutosAlarma.addItem("")
        self.cbMinutosAlarma.addItem("")
        self.cbMinutosAlarma.addItem("")
        self.cbMinutosAlarma.addItem("")
        self.cbMinutosAlarma.addItem("")
        self.cbMinutosAlarma.addItem("")
        self.cbMinutosAlarma.addItem("")
        self.cbMinutosAlarma.addItem("")
        self.cbMinutosAlarma.addItem("")
        self.cbMinutosAlarma.addItem("")
        self.cbMinutosAlarma.addItem("")
        self.cbMinutosAlarma.addItem("")
        self.cbMinutosAlarma.addItem("")
        self.cbMinutosAlarma.addItem("")
        self.cbMinutosAlarma.addItem("")
        self.cbMinutosAlarma.addItem("")
        self.cbMinutosAlarma.addItem("")
        self.cbMinutosAlarma.addItem("")
        self.cbMinutosAlarma.addItem("")
        self.cbMinutosAlarma.addItem("")
        self.cbMinutosAlarma.addItem("")
        self.cbMinutosAlarma.addItem("")
        self.cbMinutosAlarma.addItem("")
        self.cbMinutosAlarma.addItem("")
        self.cbMinutosAlarma.addItem("")
        self.cbHorasAlarma = QtWidgets.QComboBox(self.centralwidget)
        self.cbHorasAlarma.setGeometry(QtCore.QRect(50, 340, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(11)
        self.cbHorasAlarma.setFont(font)
        self.cbHorasAlarma.setObjectName("cbHorasAlarma")
        self.cbHorasAlarma.addItem("")
        self.cbHorasAlarma.addItem("")
        self.cbHorasAlarma.addItem("")
        self.cbHorasAlarma.addItem("")
        self.cbHorasAlarma.addItem("")
        self.cbHorasAlarma.addItem("")
        self.cbHorasAlarma.addItem("")
        self.cbHorasAlarma.addItem("")
        self.cbHorasAlarma.addItem("")
        self.cbHorasAlarma.addItem("")
        self.cbHorasAlarma.addItem("")
        self.cbHorasAlarma.addItem("")
        self.cbHorasAlarma.addItem("")
        self.cbHorasAlarma.addItem("")
        self.cbHorasAlarma.addItem("")
        self.cbHorasAlarma.addItem("")
        self.cbHorasAlarma.addItem("")
        self.cbHorasAlarma.addItem("")
        self.cbHorasAlarma.addItem("")
        self.cbHorasAlarma.addItem("")
        self.cbHorasAlarma.addItem("")
        self.cbHorasAlarma.addItem("")
        self.cbHorasAlarma.addItem("")
        self.cbHorasAlarma.addItem("")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(50, 400, 271, 16))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.cbSonido = QtWidgets.QComboBox(self.centralwidget)
        self.cbSonido.setGeometry(QtCore.QRect(50, 430, 211, 31))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(11)
        self.cbSonido.setFont(font)
        self.cbSonido.setObjectName("cbSonido")
        self.cbSonido.addItem("")
        self.cbSonido.addItem("")
        self.cbSonido.addItem("")
        self.cbSonido.addItem("")
        self.cbSonido.addItem("")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(50, 490, 271, 16))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.txtNombre = QtWidgets.QLineEdit(self.centralwidget)
        self.txtNombre.setGeometry(QtCore.QRect(50, 520, 211, 31))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(11)
        self.txtNombre.setFont(font)
        self.txtNombre.setObjectName("txtNombre")
        self.btnCrear = QtWidgets.QPushButton(self.centralwidget)
        self.btnCrear.setGeometry(QtCore.QRect(50, 590, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.btnCrear.setFont(font)
        self.btnCrear.setObjectName("btnCrear")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(50, 310, 41, 16))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(160, 310, 271, 16))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.btnRegresar = QtWidgets.QPushButton(self.centralwidget)
        self.btnRegresar.setGeometry(QtCore.QRect(610, 590, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.btnRegresar.setFont(font)
        self.btnRegresar.setObjectName("btnRegresar")
        self.btnActualizar = QtWidgets.QPushButton(self.centralwidget)
        self.btnActualizar.setGeometry(QtCore.QRect(330, 590, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.btnActualizar.setFont(font)
        self.btnActualizar.setObjectName("btnActualizar")
        self.btnEliminar = QtWidgets.QPushButton(self.centralwidget)
        self.btnEliminar.setGeometry(QtCore.QRect(470, 590, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.btnEliminar.setFont(font)
        self.btnEliminar.setObjectName("btnEliminar")
        self.tblAlarma = QtWidgets.QTableWidget(self.centralwidget)
        self.tblAlarma.setGeometry(QtCore.QRect(310, 280, 411, 271))
        self.tblAlarma.setObjectName("tblAlarma")
        self.tblAlarma.setColumnCount(0)
        self.tblAlarma.setRowCount(0)
        self.btnSeleccionar = QtWidgets.QPushButton(self.centralwidget)
        self.btnSeleccionar.setGeometry(QtCore.QRect(190, 590, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.btnSeleccionar.setFont(font)
        self.btnSeleccionar.setObjectName("btnSeleccionar")
        Alarma.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Alarma)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 779, 21))
        self.menubar.setObjectName("menubar")
        Alarma.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Alarma)
        self.statusbar.setObjectName("statusbar")
        Alarma.setStatusBar(self.statusbar)

        self.retranslateUi(Alarma)
        QtCore.QMetaObject.connectSlotsByName(Alarma)

    def retranslateUi(self, Alarma):
        _translate = QtCore.QCoreApplication.translate
        Alarma.setWindowTitle(_translate("Alarma", "Alarma"))
        self.label_2.setText(_translate("Alarma", "Establecer una hora de alarma"))
        self.cbMinutosAlarma.setItemText(0, _translate("Alarma", "00"))
        self.cbMinutosAlarma.setItemText(1, _translate("Alarma", "01"))
        self.cbMinutosAlarma.setItemText(2, _translate("Alarma", "02"))
        self.cbMinutosAlarma.setItemText(3, _translate("Alarma", "03"))
        self.cbMinutosAlarma.setItemText(4, _translate("Alarma", "04"))
        self.cbMinutosAlarma.setItemText(5, _translate("Alarma", "05"))
        self.cbMinutosAlarma.setItemText(6, _translate("Alarma", "06"))
        self.cbMinutosAlarma.setItemText(7, _translate("Alarma", "07"))
        self.cbMinutosAlarma.setItemText(8, _translate("Alarma", "08"))
        self.cbMinutosAlarma.setItemText(9, _translate("Alarma", "09"))
        self.cbMinutosAlarma.setItemText(10, _translate("Alarma", "10"))
        self.cbMinutosAlarma.setItemText(11, _translate("Alarma", "11"))
        self.cbMinutosAlarma.setItemText(12, _translate("Alarma", "12"))
        self.cbMinutosAlarma.setItemText(13, _translate("Alarma", "13"))
        self.cbMinutosAlarma.setItemText(14, _translate("Alarma", "14"))
        self.cbMinutosAlarma.setItemText(15, _translate("Alarma", "15"))
        self.cbMinutosAlarma.setItemText(16, _translate("Alarma", "16"))
        self.cbMinutosAlarma.setItemText(17, _translate("Alarma", "17"))
        self.cbMinutosAlarma.setItemText(18, _translate("Alarma", "18"))
        self.cbMinutosAlarma.setItemText(19, _translate("Alarma", "19"))
        self.cbMinutosAlarma.setItemText(20, _translate("Alarma", "20"))
        self.cbMinutosAlarma.setItemText(21, _translate("Alarma", "21"))
        self.cbMinutosAlarma.setItemText(22, _translate("Alarma", "22"))
        self.cbMinutosAlarma.setItemText(23, _translate("Alarma", "23"))
        self.cbMinutosAlarma.setItemText(24, _translate("Alarma", "24"))
        self.cbMinutosAlarma.setItemText(25, _translate("Alarma", "25"))
        self.cbMinutosAlarma.setItemText(26, _translate("Alarma", "26"))
        self.cbMinutosAlarma.setItemText(27, _translate("Alarma", "27"))
        self.cbMinutosAlarma.setItemText(28, _translate("Alarma", "28"))
        self.cbMinutosAlarma.setItemText(29, _translate("Alarma", "29"))
        self.cbMinutosAlarma.setItemText(30, _translate("Alarma", "30"))
        self.cbMinutosAlarma.setItemText(31, _translate("Alarma", "31"))
        self.cbMinutosAlarma.setItemText(32, _translate("Alarma", "32"))
        self.cbMinutosAlarma.setItemText(33, _translate("Alarma", "33"))
        self.cbMinutosAlarma.setItemText(34, _translate("Alarma", "34"))
        self.cbMinutosAlarma.setItemText(35, _translate("Alarma", "35"))
        self.cbMinutosAlarma.setItemText(36, _translate("Alarma", "36"))
        self.cbMinutosAlarma.setItemText(37, _translate("Alarma", "37"))
        self.cbMinutosAlarma.setItemText(38, _translate("Alarma", "38"))
        self.cbMinutosAlarma.setItemText(39, _translate("Alarma", "39"))
        self.cbMinutosAlarma.setItemText(40, _translate("Alarma", "40"))
        self.cbMinutosAlarma.setItemText(41, _translate("Alarma", "41"))
        self.cbMinutosAlarma.setItemText(42, _translate("Alarma", "42"))
        self.cbMinutosAlarma.setItemText(43, _translate("Alarma", "43"))
        self.cbMinutosAlarma.setItemText(44, _translate("Alarma", "44"))
        self.cbMinutosAlarma.setItemText(45, _translate("Alarma", "45"))
        self.cbMinutosAlarma.setItemText(46, _translate("Alarma", "46"))
        self.cbMinutosAlarma.setItemText(47, _translate("Alarma", "47"))
        self.cbMinutosAlarma.setItemText(48, _translate("Alarma", "48"))
        self.cbMinutosAlarma.setItemText(49, _translate("Alarma", "49"))
        self.cbMinutosAlarma.setItemText(50, _translate("Alarma", "50"))
        self.cbMinutosAlarma.setItemText(51, _translate("Alarma", "51"))
        self.cbMinutosAlarma.setItemText(52, _translate("Alarma", "52"))
        self.cbMinutosAlarma.setItemText(53, _translate("Alarma", "53"))
        self.cbMinutosAlarma.setItemText(54, _translate("Alarma", "54"))
        self.cbMinutosAlarma.setItemText(55, _translate("Alarma", "55"))
        self.cbMinutosAlarma.setItemText(56, _translate("Alarma", "56"))
        self.cbMinutosAlarma.setItemText(57, _translate("Alarma", "57"))
        self.cbMinutosAlarma.setItemText(58, _translate("Alarma", "58"))
        self.cbMinutosAlarma.setItemText(59, _translate("Alarma", "59"))
        self.cbHorasAlarma.setItemText(0, _translate("Alarma", "00"))
        self.cbHorasAlarma.setItemText(1, _translate("Alarma", "01"))
        self.cbHorasAlarma.setItemText(2, _translate("Alarma", "02"))
        self.cbHorasAlarma.setItemText(3, _translate("Alarma", "03"))
        self.cbHorasAlarma.setItemText(4, _translate("Alarma", "04"))
        self.cbHorasAlarma.setItemText(5, _translate("Alarma", "05"))
        self.cbHorasAlarma.setItemText(6, _translate("Alarma", "06"))
        self.cbHorasAlarma.setItemText(7, _translate("Alarma", "07"))
        self.cbHorasAlarma.setItemText(8, _translate("Alarma", "08"))
        self.cbHorasAlarma.setItemText(9, _translate("Alarma", "09"))
        self.cbHorasAlarma.setItemText(10, _translate("Alarma", "10"))
        self.cbHorasAlarma.setItemText(11, _translate("Alarma", "11"))
        self.cbHorasAlarma.setItemText(12, _translate("Alarma", "12"))
        self.cbHorasAlarma.setItemText(13, _translate("Alarma", "13"))
        self.cbHorasAlarma.setItemText(14, _translate("Alarma", "14"))
        self.cbHorasAlarma.setItemText(15, _translate("Alarma", "15"))
        self.cbHorasAlarma.setItemText(16, _translate("Alarma", "16"))
        self.cbHorasAlarma.setItemText(17, _translate("Alarma", "17"))
        self.cbHorasAlarma.setItemText(18, _translate("Alarma", "18"))
        self.cbHorasAlarma.setItemText(19, _translate("Alarma", "19"))
        self.cbHorasAlarma.setItemText(20, _translate("Alarma", "20"))
        self.cbHorasAlarma.setItemText(21, _translate("Alarma", "21"))
        self.cbHorasAlarma.setItemText(22, _translate("Alarma", "22"))
        self.cbHorasAlarma.setItemText(23, _translate("Alarma", "23"))
        self.label_3.setText(_translate("Alarma", "Sonido de Alarma"))
        self.cbSonido.setItemText(0, _translate("Alarma", "Sonido 01"))
        self.cbSonido.setItemText(1, _translate("Alarma", "Sonido 02"))
        self.cbSonido.setItemText(2, _translate("Alarma", "Sonido 03"))
        self.cbSonido.setItemText(3, _translate("Alarma", "Sonido 04"))
        self.cbSonido.setItemText(4, _translate("Alarma", "Sonido 05"))
        self.label_4.setText(_translate("Alarma", "Nombre de la Alarma"))
        self.btnCrear.setText(_translate("Alarma", "Crear"))
        self.label_5.setText(_translate("Alarma", "Horas"))
        self.label_6.setText(_translate("Alarma", "Minutos"))
        self.btnRegresar.setText(_translate("Alarma", "Regresar"))
        self.btnActualizar.setText(_translate("Alarma", "Actualizar"))
        self.btnEliminar.setText(_translate("Alarma", "Eliminar"))
        self.btnSeleccionar.setText(_translate("Alarma", "Seleccionar"))
